server:
  port: 8007

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.107.6
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: localhost
        heartbeat:
          enabled: true