server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                   # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route1               # 路由ID，没有固定规划但要求唯一，建议配合服务名
          # uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          # 断言，路径相匹配的进行路由
            - After=2020-06-10T18:50:53.592+08:00[Asia/Shanghai]

        - id: payment_route2
          # uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            # - Cookie=uname,LiXL
            # - Header=X-Request-Id,\d+
            # - Host=**.li.com

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

